[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "85yaW6LrnvErx1gvyWcTqSoaEJT1M7Q7cKaeVPV2mAEp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
